import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'English' | 'German' | 'Afrikaans' | 'Oshiwambo';

const translations: Record<Language, Record<string, string>> = {
  'English': {
    // Common
    dashboard: 'Dashboard',
    vehicles: 'My Vehicles',
    maintenance: 'Maintenance',
    bookings: 'Bookings',
    settings: 'Settings',
    search: 'Search...',
    hi: 'Hi',
    garage: "Let's check your Garage today",
    total_investment: 'Total Investment',
    service_records: 'Service Records',
    scheduled_tasks: 'Scheduled Tasks',
    notifications: 'Notifications',
    privacy_policy: 'Privacy Policy',
    legal_notice: 'Legal Notice',
    save_changes: 'Save All Changes',
    cancel: 'Cancel',
    confirm: 'Confirm',
    close: 'Close',
    loading: 'Loading...',
    retry: 'Retry',
    something_went_wrong: 'Something went wrong',
    error_occurred: 'An unexpected error occurred. Our team has been notified.',
    back_to_garage: 'Back to Garage',
    back_to_settings: 'Back to Settings',
    my_profile: 'My Profile',
    logout: 'Logout',
    signed_in_as: 'Signed in as',
    confirm_logout: 'Are you sure you want to logout?',
    confirm_logout_title: 'Sign Out?',
    confirm_logout_msg: 'Are you sure you want to sign out of your Gearhouse account?',
    yes_sign_out: 'Yes, Sign Out',
    English: 'English',
    German: 'German',
    Afrikaans: 'Afrikaans',
    Oshiwambo: 'Oshiwambo',
    'All Notifications': 'All Notifications',
    'Critical Alerts': 'Critical Alerts',
    'Bookings': 'Bookings',
    'System Updates': 'System Updates',
    'Last 24 Hours': 'Last 24 Hours',
    'Last 7 Days': 'Last 7 Days',
    'Last 30 Days': 'Last 30 Days',
    'All Time': 'All Time',
    'Urgent Maintenance Required': 'Urgent Maintenance Required',
    'Service Confirmation': 'Service Confirmation',
    'Vehicle Return Complete': 'Vehicle Return Complete',
    'System Update Successful': 'System Update Successful',
    'Speed Threshold Alert': 'Speed Threshold Alert',
    'SCHEDULE NOW': 'SCHEDULE NOW',
    'DISMISS': 'DISMISS',

    // Settings
    notif_settings: 'Choose what you want to be notified about',
    email_notif: 'Email Notifications',
    email_notif_sub: 'Receive summary reports and alerts via email',
    push_notif: 'Push Notifications',
    push_notif_sub: 'Real-time alerts on your browser/device',
    maint_alerts: 'Maintenance Alerts',
    maint_alerts_sub: 'Get notified when a vehicle needs urgent service',
    promo_offers: 'Promotional Offers',
    promo_offers_sub: 'Stay updated on service discounts and rewards',
    preferences: 'Preferences',
    customize_ui: 'Customize the interface and display',
    theme_mode: 'Theme Mode',
    light: 'Light',
    dark: 'Dark',
    language_label: 'Language',
    security_support: 'Security & Support',
    privacy_sub: 'Manage your data and privacy settings',
    legal_sub: 'Terms of service and legal agreement',

    // Dashboard
    maintenance_activity: 'Maintenance Activity Overview',
    alerts: 'Alerts',
    open_alerts: 'Open Alerts',
    closed_alerts: 'Closed Alerts',
    last_7_months: 'Last 7 months',
    vehicle_status: 'Vehicle Status',
    no: 'No',
    vehicle: 'Vehicle',
    last_service: 'Last Service',
    mileage: 'Mileage',
    risk: 'Risk',
    limited_offer: 'Limited Time Offer',
    off_20: '20% Off',
    brake_service: 'Brake Service',
    book_now: 'Book Now',
    ai_insight: 'AI Insight',
    ai_prediction: 'Maintenance likely needed in 2 weeks for 3 vehicles',
    view_details: 'View Details',
    dismiss: 'Dismiss',

    // My Vehicles
    add_vehicle: 'Add Vehicle',
    empty_slot: 'Empty Slot',
    vin: 'VIN',
    odometer: 'Odometer',
    pickup: 'Pickup',
    suv: 'SUV',
    sedan: 'Sedan',
    van: 'Van',
    truck: 'Truck',
    diesel: 'Diesel',
    gasoline: 'Gasoline',
    electric: 'Electric',
    hybrid: 'Hybrid',
    vehicle_info: 'Vehicle Information',
    make: 'Make',
    model: 'Model',
    year: 'Year',
    engine_cc: 'Engine CC',
    engine_type: 'Engine Type',
    transmission: 'Transmission',
    fuel_capacity: 'Fuel Capacity',
    last_service_date: 'Last Service Date',
    in_operation: 'In Operation',
    edit_info: 'Edit Info',
    current_mileage: 'Current Mileage',
    license_plate: 'License Plate',
    vehicle_type: 'Vehicle Type',
    fuel_type: 'Fuel Type',
    service_interval: 'Service Interval',
    vehicle_image: 'Vehicle Image',
    upload_vehicle_image: 'Upload Vehicle Image',
    notes: 'Notes',
    add_additional_details: 'Add any additional details...',
    image_uploaded: 'Image uploaded!',
    upload_failed: 'Upload failed',
    vehicle_added_successfully: 'Vehicle added successfully!',
    failed_to_add_vehicle: 'Failed to add vehicle',
    changes_saved: 'Changes saved!',
    failed_to_update: 'Failed to update',
    delete_vehicle_confirmation: 'Delete this vehicle? This action cannot be undone.',
    vehicle_removed: 'Vehicle removed',
    failed_to_delete: 'Failed to delete',
    edit_vehicle: 'Edit Vehicle',
    uploading: 'Uploading...',
    replace_image: 'Replace Image',
    maintenance_summary: 'Maintenance Summary',
    next_service_due: 'Next Service Due',
    health_score: 'Health Score',
    delete_vehicle: 'Delete Vehicle',
    vehicle_information: 'Vehicle Information',
    select: 'Select',

    // Maintenance
    total_logs: 'Total Logs',
    active_alerts: 'Active Alerts',
    completed_ytd: 'Completed (YTD)',
    ai_predicted_30d: 'AI-Predicted (30D)',
    all_vehicles: 'All Vehicles',
    export: 'Export',
    add_service: 'Add Service',
    next_maint: 'Next Maintenance',
    est_cost: 'Est. Cost',
    confidence: 'Confidence',
    upcoming: 'Upcoming',
    window_30d: '30D Window',
    maint_tip: 'Maintenance Tip',
    assistance: 'Need Assistance?',
    call_help: 'Call Roadside Help',
    delete_entry: 'Delete Entry',
    update_service: 'Update Service',
    service_cost: 'Service Cost',
    tech_loc: 'Technician / Location',
    service_details: 'Service Details',
    status: 'Status',
    date: 'Date',
    record_deleted: 'Record deleted',
    failed_to_delete_record: 'Failed to delete record',
    delete_record_confirmation: 'Are you sure you want to delete this record?',
    status_updated: 'Status updated to',
    failed_to_update_status: 'Failed to update status',
    alert_status_updated: 'Alert status updated',
    service: 'Service',
    recorded_on: 'Recorded on',
    mileage_at_service: 'Mileage at Service',
    service_summary: 'Service Summary',
    type: 'Type',
    total_cost: 'Total Cost',
    detailed_notes: 'Detailed Notes',
    set_status: 'Set Status',
    select_vehicle: 'Select Vehicle',
    oil_change: 'Oil Change',
    brake_change: 'Brake Change',
    engine_check: 'Engine Check',
    edit_service: 'Edit Service',
    go_to_login: 'Go to Login',
    from_last_week: 'from last week',
    investment: 'investment',
    records: 'records',
    tasks: 'tasks',
    urgent_maintenance_required: 'Urgent Maintenance Required',
    service_confirmation: 'Service Confirmation',
    vehicle_return_complete: 'Vehicle Return Complete',
    system_update_successful: 'System Update Successful',
    speed_threshold_alert: 'Speed Threshold Alert',
    schedule_now: 'SCHEDULE NOW',
    dismiss_upper: 'DISMISS',
    all_notif_cat: 'All Notifications',
    crit_alerts_cat: 'Critical Alerts',
    bookings_cat: 'Bookings',
    sys_updates_cat: 'System Updates',
    last_24h: 'Last 24 Hours',
    last_7d: 'Last 7 Days',
    last_30d: 'Last 30 Days',
    all_time_dr: 'All Time',
    maintenance_forecast: 'Maintenance Forecast',
    detailed_analysis: 'Detailed Analysis',
    schedule_all_services: 'Schedule All Services',
    risk_none: 'None',
    risk_low: 'Low',
    risk_medium: 'Medium',
    risk_high: 'High',
    brake_wear: 'Brake Wear',
    engine_oil: 'Engine Oil',
    tire_health: 'Tire Health',
    battery: 'Battery',
    ai_garage_insights: 'AI Garage Insights',
    predictive_analysis: 'Predictive maintenance analysis for your fleet',

    // Bookings
    bookings_title: 'Service Bookings',
    new_booking: 'New Booking',
    calendar: 'Calendar',
    list_view: 'List View',
    today: 'Today',
    month: 'Month',
    week: 'Week',
    day: 'Day',
    time: 'Time',
    more: 'more',
    service_center: 'Service Center',
    service_details_title: 'Service Details',
    select_service_center: 'Select Service Center',
    location_address: 'Location Address',
    preferred_date: 'Preferred Date',
    preferred_time_slot: 'Preferred Time Slot',
    special_instructions: 'Special Instructions',
    confirm_booking: 'Confirm Booking',
    booking_summary: 'Booking Summary',
    estimated_duration: 'Estimated Duration',
    estimated_cost_label: 'Estimated Cost',
    cost_estimate_note: 'Cost is an estimate based on standard labor rates and parts. Final price may vary.',
    technician: 'Technician',
    time_slot: 'Time Slot',
    location: 'Location',
    address: 'Address',
    close_details: 'Close Details',
    service_type: 'Service Type',
    tire_rotation: 'Tire Rotation',
    full_inspection: 'Full Inspection',
    appointment_booked: 'Workshop appointment booked!',
    booking_failed: 'Booking failed',
    session_not_found: 'User session not found. Please log in again.',
    gearhouse_garage_placeholder: 'e.g. Gearhouse Downtown Garage',
    main_street_placeholder: '123 Main St, Downtown',
    add_special_instructions: 'Add any specific details or concerns...',
    main_street_auto: 'Main Street Auto',
    confirmed: 'Confirmed',
    downtown_address: '123 Downtown St, Suite 405',
    delete_record_confirm: 'Are you sure you want to delete this record?',
    maint_added_success: 'Maintenance added successfully',
    maint_update_success: 'Maintenance updated successfully',
    failed_add_record: 'Failed to add record',
    failed_update_record: 'Failed to update record',
    failed_delete_record: 'Failed to delete record',
    status_updated_to: 'Status updated to',
    alert_status_updated_msg: 'Alert status updated',
    completed_status: 'Completed',
    open_status: 'Open',
    overdue_status: 'Overdue',
    optimize_schedule: 'Optimize Schedule',
    no_upcoming_tasks: 'No upcoming tasks',
    service_in: 'Service in',
    est_cost_upper: 'EST. COST',
    confidence_upper: 'CONFIDENCE',
    thirty_day_window: '30D Window',
    pickup_truck_val: 'Pickup Truck',
    toyota_hilux_db_val: 'Toyota Hilux Double Cab',
    engine_cc_val: '2,755 cc',
    engine_turbo_val: '2.8L Diesel Turbo',
    trans_auto_val: '6-Speed Automatic',
    fuel_cap_val: '80 Liters',
    oct_2024_val: '12 Oct 2024',
    next_serv_km_val: '55,200 km',
    low_risk_val: 'LOW',
    medium_risk_val: 'MEDIUM',
    high_risk_val: 'HIGH',
    make_placeholder: 'e.g. Toyota',
    model_placeholder: 'e.g. Hilux',
    plate_placeholder: 'ABC-1234',
    upload_failed_msg: 'Failed to upload image',

    // Notifications
    all_notif: 'All Notifications',
    unread: 'Unread',
    archived: 'Archived',
    mark_all_read: 'Mark all as read',
    no_notif: 'No notifications found',
    unread_alert: 'unread alert',
    unread_alerts: 'unread alerts',
    unread_count_part1: 'You have',
    all_caught_up: 'All caught up!',
    no_notif_match: 'No notifications match your current filters.',
    load_older: 'Load older notifications',
    categories_label: 'Categories',
    date_range_label: 'Date Range',
    apply_filters: 'Apply Filters',
    clear_all: 'Clear All',
    filters: 'Filters',
    pro_tip: 'PRO TIP',
    sms_alerts_note: 'You can set automated SMS alerts for Critical and Urgent notifications in your Account Settings.',
    critical_alerts: 'Critical Alerts',
    system_updates: 'System Updates',
    last_24_hours: 'Last 24 Hours',
    last_7_days: 'Last 7 Days',
    last_30_days: 'Last 30 Days',
    all_time: 'All Time',
    all_notifications: 'All Notifications',

    // GearBot
    gearbot: 'Gearbot',
    fleet_assistant: 'Fleet Intelligence Assistant',
    ask_gearbot: 'Ask Gearbot...',
    listening_label: 'Listening...',
    auto_send_note: 'Auto-sending after 4s of silence...',
    ai_initial_msg: "Hey! I'm Gearbot, your fleet intelligence assistant. How can I help you today?",
    ai_resp_1: "Your fleet is currently at 92% operational capacity. 2 vehicles require attention.",
    ai_resp_2: "Based on maintenance history, Vehicle GH-102 is due for a service check within the next 3 days.",
    ai_resp_3: "I've detected 1 critical alert: a brake wear warning on Tesla Model 3 (GH-102). Schedule maintenance immediately.",
    ai_resp_4: "Fleet stats: 14 active vehicles, 2 in maintenance, 1 booking pending for tomorrow.",
    ai_resp_5: "GH-056 speed threshold was exceeded on M1 Highway yesterday. Driver: Mike Ross.",
    fleet_owner: "Fleet Owner",
    open_gearbot: "Open Gearbot AI",
    send_message: "Send message",

    // My Account
    profile: 'Profile',
    security: 'Security',
    full_name: 'Full Name',
    email_address: 'Email Address',
    phone_number: 'Phone Number',
    change_password: 'Change Password',
    sign_out: 'Sign Out',
    profile_updated_successfully: 'Profile updated successfully!',
    manage_profile: 'Manage your personal profile and security',
    owner_manager: 'Vehicle Owner & Fleet Manager',
    active: 'Active',
    owner: 'Owner',
    download_profile_data: 'Download Profile Data',
    personal_details: 'Personal Details',
    first_name: 'First Name',
    last_name: 'Last Name',
    account_security: 'Account Security',
    update_credentials: 'Update your account credentials',
    two_factor_auth: 'Two-Factor Authentication',
    extra_security_layer: 'Add an extra layer of security',
    deactivate_account: 'Deactivate Account',
    current_password: 'Current Password',
    new_password: 'New Password',
    confirm_password: 'Confirm New Password',
    password_changed_successfully: 'Password changed successfully!',
    passwords_do_not_match: 'Passwords do not match',
    deactivate_confirmation: 'Are you sure you want to deactivate your account? This action cannot be undone.',
    account_deactivated_successfully: 'Account deactivated successfully.',
    upload_profile_image: 'Upload Profile Image',
    image_uploaded_successfully: 'Image uploaded successfully!',
    failed_to_upload_image: 'Failed to upload image.',

    // Privacy & Legal
    last_updated: 'Last Updated',
    privacy_1_title: '1. Information We Collect',
    privacy_1_text: 'At Gearhouse, we prioritize your privacy. We collect information necessary to provide our fleet management services, including vehicle data, maintenance logs, and user profile information.',
    privacy_2_title: '2. How We Use Data',
    privacy_2_text: 'We use the data we collect to provide, maintain, and improve our services, including:',
    privacy_2_li1: 'Providing vehicle health alerts and maintenance predictions.',
    privacy_2_li2: 'Processing transactions and managing your account.',
    privacy_2_li3: 'Communicating with you about updates and security.',
    privacy_3_title: '3. Data Security',
    privacy_3_text: 'We implement industry-standard security measures to protect your professional and vehicle data. However, no method of transmission over the internet is 100% secure.',
    i_understand: 'I Understand',
    legal_version: 'Version 2.4 — 2026 Release',
    legal_1_title: 'Legal Agreement',
    legal_1_text: 'This application is provided by P3 Namibia. By using this service, you agree to comply with all local and international laws regarding fleet management and data privacy.',
    legal_2_title: 'Intellectual Property',
    legal_2_text: 'The Gearhouse platform, its logo, and design elements are the intellectual property of Gearhouse Inc. and are protected by copyright laws.',
    legal_3_title: 'Limitation of Liability',
    legal_3_text: 'We strive for 100% accuracy, but we are not liable for any discrepancies in automated maintenance reporting or GPS tracking.',
    acknowledge_terms: 'Acknowledge Terms'
  },
  'German': {
    dashboard: 'Instrumententafel',
    vehicles: 'Meine Fahrzeuge',
    maintenance: 'Wartung',
    bookings: 'Buchungen',
    settings: 'Einstellungen',
    search: 'Suchen...',
    hi: 'Hallo',
    garage: 'Schauen wir uns heute Ihre Garage an',
    total_investment: 'Gesamtinvestition',
    service_records: 'Service-Unterlagen',
    scheduled_tasks: 'Geplante Aufgaben',
    notifications: 'Benachrichtigungen',
    privacy_policy: 'Datenschutzrichtlinie',
    legal_notice: 'Impressum',
    save_changes: 'Alle Änderungen speichern',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen',
    close: 'Schließen',
    loading: 'Laden...',
    retry: 'Wiederholen',
    something_went_wrong: 'Etwas ist schief gelaufen',
    error_occurred: 'Ein unerwarteter Fehler ist aufgetreten. Unser Team wurde benachrichtigt.',
    back_to_garage: 'Zurück zum Garage',
    back_to_settings: 'Zurück zu Einstellungen',
    my_profile: 'Mein Profil',
    logout: 'Abmelden',
    signed_in_as: 'Angemeldet als',
    confirm_logout: 'Sind Sie sicher, dass Sie sich abmelden möchten?',
    confirm_logout_title: 'Abmelden?',
    confirm_logout_msg: 'Sind Sie sicher, dass Sie sich von Ihrem Gearhouse-Konto abmelden möchten?',
    yes_sign_out: 'Ja, Abmelden',
    English: 'Englisch',
    German: 'Deutsch',
    Afrikaans: 'Afrikaans',
    Oshiwambo: 'Oshiwambo',
    'All Notifications': 'Alle Benachrichtigungen',
    'Critical Alerts': 'Kritische Warnungen',
    'Bookings': 'Buchungen',
    'System Updates': 'System-Updates',
    'Last 24 Hours': 'Letzte 24 Stunden',
    'Last 7 Days': 'Letzte 7 Tage',
    'Last 30 Days': 'Letzte 30 Tage',
    'All Time': 'Alle Zeit',
    'Urgent Maintenance Required': 'Dringende Wartung erforderlich',
    'Service Confirmation': 'Service-Bestätigung',
    'Vehicle Return Complete': 'Fahrzeugrückgabe abgeschlossen',
    'System Update Successful': 'System-Update erfolgreich',
    'Speed Threshold Alert': 'Geschwindigkeitsüberschreitung',
    'SCHEDULE NOW': 'JETZT PLANEN',
    'DISMISS': 'VERWERFEN',

    notif_settings: 'Wählen Sie aus, worüber Sie benachrichtigt werden möchten',
    email_notif: 'E-Mail Benachrichtigungen',
    email_notif_sub: 'Zusammenfassende Berichte und Warnungen per E-Mail erhalten',
    push_notif: 'Push-Benachrichtigungen',
    push_notif_sub: 'Echtzeit-Warnungen auf Ihrem Browser/Gerät',
    maint_alerts: 'Wartungswarnungen',
    maint_alerts_sub: 'Benachrichtigt werden, wenn ein Fahrzeug dringend gewartet werden muss',
    promo_offers: 'Werbeangebote',
    promo_offers_sub: 'Bleiben Sie über Service-Rabatte und Belohnungen auf dem Laufenden',
    preferences: 'Präferenzen',
    customize_ui: 'Passen Sie die Schnittstelle und Anzeige an',
    theme_mode: 'Themenmodus',
    light: 'Hell',
    dark: 'Dunkel',
    language_label: 'Sprache',
    security_support: 'Sicherheit & Unterstützung',
    privacy_sub: 'Verwalten Sie Ihre Daten- und Datenschutzeinstellungen',
    legal_sub: 'Nutzungsbedingungen und rechtliche Vereinbarung',

    // Maintenance Overview
    maintenance_activity: 'Übersicht der Wartungsaktivitäten',
    alerts: 'Warnungen',
    open_alerts: 'Offene Warnungen',
    closed_alerts: 'Geschlossene Warnungen',
    last_7_months: 'Letzte 7 Monate',
    vehicle_status: 'Fahrzeugstatus',
    no: 'Nr.',
    vehicle: 'Fahrzeug',
    last_service: 'Letzter Service',
    mileage: 'Kilometerstand',
    risk: 'Risiko',
    limited_offer: 'Befristetes Angebot',
    off_20: '20% Rabatt',
    brake_service: 'Bremsenservice',
    book_now: 'Jetzt buchen',
    ai_insight: 'KI-Einblick',
    ai_prediction: 'Wartung wahrscheinlich in 2 Wochen für 3 Fahrzeuge erforderlich',
    view_details: 'Details anzeigen',
    dismiss: 'Verwerfen',

    add_vehicle: 'Fahrzeug hinzufügen',
    empty_slot: 'Leerer Sendeplatz',
    vin: 'Fahrgestellnummer',
    odometer: 'Kilometerzähler',
    pickup: 'Pickup',
    suv: 'SUV',
    sedan: 'Limousine',
    van: 'Van',
    truck: 'LKW',
    diesel: 'Diesel',
    gasoline: 'Benzin',
    electric: 'Elektro',
    hybrid: 'Hybrid',
    vehicle_info: 'Fahrzeug-Informationen',
    make: 'Marke',
    model: 'Modell',
    year: 'Jahr',
    engine_cc: 'Hubraum',
    engine_type: 'Motortyp',
    transmission: 'Getriebe',
    fuel_capacity: 'Kraftstofftank',
    last_service_date: 'Letztes Servicedatum',
    in_operation: 'In Betrieb',
    edit_info: 'Info bearbeiten',
    current_mileage: 'Aktueller Kilometerstand',
    license_plate: 'Kennzeichen',
    vehicle_type: 'Fahrzeugtyp',
    fuel_type: 'Kraftstofftyp',
    service_interval: 'Serviceintervall',
    vehicle_image: 'Fahrzeugbild',
    upload_vehicle_image: 'Fahrzeugbild hochladen',
    notes: 'Notizen',
    add_additional_details: 'Zusätzliche Details hinzufügen...',
    image_uploaded: 'Bild hochgeladen!',
    upload_failed: 'Upload fehlgeschlagen',
    vehicle_added_successfully: 'Fahrzeug erfolgreich hinzugefügt!',
    failed_to_add_vehicle: 'Fahrzeug konnte nicht hinzugefügt werden',
    changes_saved: 'Änderungen gespeichert!',
    failed_to_update: 'Update fehlgeschlagen',
    delete_vehicle_confirmation: 'Dieses Fahrzeug löschen? Dies kann nicht rückgängig gemacht werden.',
    vehicle_removed: 'Fahrzeug entfernt',
    failed_to_delete: 'Löschen fehlgeschlagen',
    edit_vehicle: 'Fahrzeug bearbeiten',
    uploading: 'Laden...',
    replace_image: 'Bild ersetzen',
    maintenance_summary: 'Wartungszusammenfassung',
    next_service_due: 'Nächster Service fällig',
    health_score: 'Gesundheitswert',
    delete_vehicle: 'Fahrzeug löschen',
    vehicle_information: 'Fahrzeug-Informationen',
    select: 'Auswählen',

    total_logs: 'Gesamtprotokolle',
    active_alerts: 'Aktive Warnungen',
    completed_ytd: 'Abgeschlossen (YTD)',
    ai_predicted_30d: 'KI-Prognose (30T)',
    all_vehicles: 'Alle Fahrzeuge',
    export: 'Exportieren',
    add_service: 'Service hinzufügen',
    next_maint: 'Nächste Wartung',
    est_cost: 'Geschätzte Kosten',
    confidence: 'Vertrauen',
    upcoming: 'Anstehend',
    window_30d: '30-Tage Fenster',
    maint_tip: 'Wartungstipp',
    assistance: 'Benötigen Sie Hilfe?',
    call_help: 'Pannenhilfe rufen',
    delete_entry: 'Eintrag löschen',
    update_service: 'Service aktualisieren',
    service_cost: 'Servicekosten',
    tech_loc: 'Techniker / Standort',
    service_details: 'Service-Details',
    status: 'Status',
    date: 'Datum',
    record_deleted: 'Eintrag gelöscht',
    failed_to_delete_record: 'Eintrag konnte nicht gelöscht werden',
    delete_record_confirmation: 'Sind Sie sicher, dass Sie diesen Eintrag löschen möchten?',
    status_updated: 'Status aktualisiert auf',
    failed_to_update_status: 'Status konnte nicht aktualisiert werden',
    alert_status_updated: 'Warnstatus aktualisiert',
    service: 'Service',
    recorded_on: 'Aufgezeichnet am',
    mileage_at_service: 'Kilometerstand beim Service',
    service_summary: 'Service-Zusammenfassung',
    type: 'Typ',
    total_cost: 'Gesamtkosten',
    detailed_notes: 'Detaillierte Notizen',
    set_status: 'Status festlegen',
    select_vehicle: 'Fahrzeug auswählen',
    oil_change: 'Ölwechsel',
    brake_change: 'Bremsenwechsel',
    engine_check: 'Motorprüfung',
    edit_service: 'Service bearbeiten',
    go_to_login: 'Zum Login gehen',
    from_last_week: 'seit letzter Woche',
    investment: 'Investition',
    records: 'Protokolle',
    tasks: 'Aufgaben',
    urgent_maintenance_required: 'Dringende Wartung erforderlich',
    service_confirmation: 'Servicebestätigung',
    vehicle_return_complete: 'Fahrzeugrückgabe abgeschlossen',
    system_update_successful: 'Systemaktualisierung erfolgreich',
    speed_threshold_alert: 'Geschwindigkeitsüberschreitung',
    schedule_now: 'JETZT PLANEN',
    dismiss_upper: 'VERWERFEN',
    all_notif_cat: 'Alle Benachrichtigungen',
    crit_alerts_cat: 'Kritische Warnungen',
    bookings_cat: 'Buchungen',
    sys_updates_cat: 'Systemaktualisierungen',
    last_24h: 'Letzte 24 Stunden',
    last_7d: 'Letzte 7 Tage',
    last_30d: 'Letzte 30 Tage',
    all_time_dr: 'Gesamte Zeit',
    maintenance_forecast: 'Wartungsprognose',
    detailed_analysis: 'Detaillierte Analyse',
    schedule_all_services: 'Alle Services planen',
    risk_none: 'Keine',
    risk_low: 'Niedrig',
    risk_medium: 'Mittel',
    risk_high: 'Hoch',
    brake_wear: 'Bremsbeläge',
    engine_oil: 'Motoröl',
    tire_health: 'Reifenzustand',
    battery: 'Batterie',
    ai_garage_insights: 'KI-Garage-Einblicke',
    predictive_analysis: 'Prädiktive Wartungsanalyse für Ihre Flotte',

    bookings_title: 'Service-Buchungen',
    new_booking: 'Neue Buchung',
    calendar: 'Kalender',
    list_view: 'Listenansicht',
    today: 'Heute',
    month: 'Monat',
    week: 'Woche',
    day: 'Tag',
    time: 'Zeit',
    more: 'mehr',
    service_center: 'Servicezentrum',
    service_details_title: 'Service-Details',
    select_service_center: 'Servicezentrum auswählen',
    location_address: 'Standortadresse',
    preferred_date: 'Bevorzugtes Datum',
    preferred_time_slot: 'Bevorzugtes Zeitfenster',
    special_instructions: 'Besondere Anweisungen',
    confirm_booking: 'Buchung bestätigen',
    booking_summary: 'Buchungszusammenfassung',
    estimated_duration: 'Geschätzte Dauer',
    estimated_cost_label: 'Geschätzte Kosten',
    cost_estimate_note: 'Kosten sind eine Schätzung basierend auf Standardarbeitssätzen und Teilen. Endpreis kann variieren.',
    technician: 'Techniker',
    time_slot: 'Zeitfenster',
    location: 'Standort',
    address: 'Adresse',
    close_details: 'Details schließen',
    service_type: 'Serviceart',
    tire_rotation: 'Reifenrotation',
    full_inspection: 'Vollständige Inspektion',
    appointment_booked: 'Werkstatttermin gebucht!',
    booking_failed: 'Buchung fehlgeschlagen',
    session_not_found: 'Benutzersitzung nicht gefunden. Bitte melden Sie sich erneut an.',
    gearhouse_garage_placeholder: 'z.B. Gearhouse Downtown Garage',
    main_street_placeholder: 'Hauptstraße 123, Zentrum',
    add_special_instructions: 'Fügen Sie spezifische Details oder Bedenken hinzu...',
    main_street_auto: 'Hauptstadt-Garage',
    confirmed: 'Bestätigt',
    downtown_address: 'Hauptstraße 123, Suite 405',
    delete_record_confirm: 'Sind Sie sicher, dass Sie diesen Datensatz löschen möchten?',
    maint_added_success: 'Wartung erfolgreich hinzugefügt',
    maint_update_success: 'Wartung erfolgreich aktualisiert',
    failed_add_record: 'Fehler beim Hinzufügen des Datensatzes',
    failed_update_record: 'Fehler beim Aktualisieren des Datensatzes',
    failed_delete_record: 'Fehler beim Löschen des Datensatzes',
    status_updated_to: 'Status aktualisiert auf',
    alert_status_updated_msg: 'Warnstatus aktualisiert',
    completed_status: 'Abgeschlossen',
    open_status: 'Offen',
    overdue_status: 'Überfällig',
    optimize_schedule: 'Zeitplan optimieren',
    no_upcoming_tasks: 'Keine anstehenden Aufgaben',
    service_in: 'Service in',
    est_cost_upper: 'GESCH. KOSTEN',
    confidence_upper: 'VERTRAUEN',
    thirty_day_window: '30-Tage-Fenster',
    pickup_truck_val: 'Pritschenwagen',
    toyota_hilux_db_val: 'Toyota Hilux Doppelkabine',
    engine_cc_val: '2.755 ccm',
    engine_turbo_val: '2,8-Liter-Diesel-Turbo',
    trans_auto_val: '6-Gang-Automatik',
    fuel_cap_val: '80 Liter',
    oct_2024_val: '12. Okt. 2024',
    next_serv_km_val: '55.200 km',
    low_risk_val: 'NIEDRIG',
    medium_risk_val: 'MITTEL',
    high_risk_val: 'HOCH',
    make_placeholder: 'z.B. Toyota',
    model_placeholder: 'z.B. Hilux',
    plate_placeholder: 'ABC-1234',
    upload_failed_msg: 'Fehler beim Hochladen des Bildes',

    all_notif: 'Alle Benachrichtigungen',
    unread: 'Ungelesen',
    archived: 'Archiviert',
    mark_all_read: 'Alle als gelesen markieren',
    no_notif: 'Keine Benachrichtigungen gefunden',
    unread_alert: 'ungelesene Warnung',
    unread_alerts: 'ungelesene Warnungen',
    unread_count_part1: 'Sie haben',
    all_caught_up: 'Alles erledigt!',
    no_notif_match: 'Keine Benachrichtigungen entsprechen Ihren aktuellen Filtern.',
    load_older: 'Ältere Benachrichtigungen laden',
    categories_label: 'Kategorien',
    date_range_label: 'Datumsbereich',
    apply_filters: 'Filter anwenden',
    clear_all: 'Alles löschen',
    filters: 'Filter',
    pro_tip: 'PROFI-TIPP',
    sms_alerts_note: 'Sie können automatische SMS-Warnungen für kritische und dringende Benachrichtigungen in Ihren Kontoeinstellungen festlegen.',
    critical_alerts: 'Kritische Warnungen',
    system_updates: 'System-Updates',
    last_24_hours: 'Letzte 24 Stunden',
    last_7_days: 'Letzte 7 Tage',
    last_30_days: 'Letzte 30 Tage',
    all_time: 'Alle Zeit',
    all_notifications: 'Alle Benachrichtigungen',

    // GearBot
    gearbot: 'Gearbot',
    fleet_assistant: 'Flottenintelligenz-Assistent',
    ask_gearbot: 'Fragen Sie Gearbot...',
    listening_label: 'Hören...',
    auto_send_note: 'Automatisches Senden nach 4s Stille...',
    ai_initial_msg: "Hallo! Ich bin Gearbot, dein Flottenintelligenz-Assistent. Wie kann ich dir heute helfen?",
    ai_resp_1: "Deine Flotte ist derzeit zu 92% einsatzbereit. 2 Fahrzeuge benötigen Aufmerksamkeit.",
    ai_resp_2: "Basierend auf der Wartungshistorie ist für Fahrzeug GH-102 innerhalb der nächsten 3 Tage eine Serviceprüfung fällig.",
    ai_resp_3: "Ich habe 1 kritische Warnung erkannt: eine Bremsenverschleißwarnung beim Tesla Model 3 (GH-102). Instandhaltung sofort planen.",
    ai_resp_4: "Flottenstatistik: 14 aktive Fahrzeuge, 2 in der Wartung, 1 Buchung steht für morgen an.",
    ai_resp_5: "Der Schwellenwert für die Geschwindigkeit von GH-056 wurde gestern auf der Autobahn M1 überschritten. Fahrer: Mike Ross.",
    fleet_owner: "Flottenbesitzer",
    open_gearbot: "Gearbot KI öffnen",
    send_message: "Nachricht senden",

    profile: 'Profil',
    security: 'Sicherheit',
    full_name: 'Vollständiger Name',
    email_address: 'E-Mail Adresse',
    phone_number: 'Telefonnummer',
    change_password: 'Passwort ändern',
    sign_out: 'Abmelden',
    profile_updated_successfully: 'Profil erfolgreich aktualisiert!',
    manage_profile: 'Verwalten Sie Ihr persönliches Profil und Ihre Sicherheit',
    owner_manager: 'Fahrzeugbesitzer & Flottenmanager',
    active: 'Aktiv',
    owner: 'Besitzer',
    download_profile_data: 'Profildaten herunterladen',
    personal_details: 'Persönliche Details',
    first_name: 'Vorname',
    last_name: 'Nachname',
    account_security: 'Kontosicherheit',
    update_credentials: 'Aktualisieren Sie Ihre Zugangsdaten',
    two_factor_auth: 'Zwei-Faktor-Authentifizierung',
    extra_security_layer: 'Fügen Sie eine zusätzliche Sicherheitsebene hinzu',
    deactivate_account: 'Konto deaktivieren',
    current_password: 'Aktuelles Passwort',
    new_password: 'Neues Passwort',
    confirm_password: 'Neues Passwort bestätigen',
    password_changed_successfully: 'Passwort erfolgreich geändert!',
    passwords_do_not_match: 'Passwörter stimmen nicht überein',
    deactivate_confirmation: 'Sind Sie sicher, dass Sie Ihr Konto deaktivieren möchten? Dies kann nicht rückgängig gemacht werden.',
    account_deactivated_successfully: 'Konto erfolgreich deaktiviert.',
    upload_profile_image: 'Profilbild hochladen',
    image_uploaded_successfully: 'Bild erfolgreich hochgeladen!',
    failed_to_upload_image: 'Bild-Upload fehlgeschlagen.',

    last_updated: 'Zuletzt aktualisiert',
    privacy_1_title: '1. Informationen, die wir sammeln',
    privacy_1_text: 'Bei Gearhouse hat Ihre Privatsphäre Priorität. Wir sammeln Informationen, die für die Bereitstellung unserer Flottenmanagement-Dienste erforderlich sind, einschließlich Fahrzeugdaten, Wartungsprotokolle und Benutzerprofilinformationen.',
    privacy_2_title: '2. Wie wir Daten verwenden',
    privacy_2_text: 'Wir verwenden die gesammelten Daten, um unsere Dienste bereitzustellen, zu warten und zu verbessern, einschließlich:',
    privacy_2_li1: 'Bereitstellung von Fahrzeugzustandswarnungen und Wartungsprognosen.',
    privacy_2_li2: 'Abwicklung von Transaktionen und Verwaltung Ihres Kontos.',
    privacy_2_li3: 'Kommunikation mit Ihnen über Updates und Sicherheit.',
    privacy_3_title: '3. Datensicherheit',
    privacy_3_text: 'Wir implementieren branchenübliche Sicherheitsmaßnahmen zum Schutz Ihrer Berufs- und Fahrzeugdaten. Keine Übertragungsmethode über das Internet ist jedoch zu 100% sicher.',
    i_understand: 'Ich verstehe',
    legal_version: 'Version 2.4 — 2026 Veröffentlichung',
    legal_1_title: 'Rechtliche Vereinbarung',
    legal_1_text: 'Diese Anwendung wird von P3 Namibia bereitgestellt. Durch die Nutzung dieses Dienstes erklären Sie sich damit einverstanden, alle lokalen und internationalen Gesetze zum Flottenmanagement und zum Datenschutz einzuhalten.',
    legal_2_title: 'Geistiges Eigentum',
    legal_2_text: 'Die Gearhouse-Plattform, ihr Logo und ihre Designelemente sind geistiges Eigentum von Gearhouse Inc. und durch Urheberrechtsgesetze geschützt.',
    legal_3_title: 'Haftungsbeschränkung',
    legal_3_text: 'Wir bemühen uns um 100%ige Genauigkeit, sind jedoch nicht haftbar für Unstimmigkeiten bei der automatisierten Wartungsberichterstattung oder dem GPS-Tracking.',
    acknowledge_terms: 'Bedingungen anerkennen'
  },
  'Afrikaans': {
    dashboard: 'Kontroleskerm',
    vehicles: 'My Voertuie',
    maintenance: 'Instandhouding',
    bookings: 'Besprekings',
    settings: 'Instellings',
    search: 'Soek...',
    hi: 'Haai',
    garage: 'Kom ons kyk vandag na jou motorhuis',
    total_investment: 'Totale Belegging',
    service_records: 'Diensrekords',
    scheduled_tasks: 'Beplande Take',
    notifications: 'Kennisgewings',
    privacy_policy: 'Privaatheidsbeleid',
    legal_notice: 'Regskennisgewing',
    save_changes: 'Stoor Alle Veranderinge',
    cancel: 'Kanselleer',
    confirm: 'Bevestig',
    close: 'Maak toe',
    loading: 'Laai tans...',
    retry: 'Probeer weer',
    something_went_wrong: 'Iets het fout gegaan',
    error_occurred: 'n Onverwagte fout het voorgekom. Ons span is in kennis gestel.',
    back_to_garage: 'Terug na Motorhuis',
    back_to_settings: 'Terug na Instellings',
    my_profile: 'My Profiel',
    logout: 'Teken uit',
    signed_in_as: 'Aangemeld as',
    confirm_logout: 'Is jy seker jy wil uitteken?',
    confirm_logout_title: 'Teken Uit?',
    confirm_logout_msg: 'Is jy seker jy wil uitteken uit jou Gearhouse-rekening?',
    yes_sign_out: 'Ja, Teken Uit',
    English: 'Engels',
    German: 'Duits',
    Afrikaans: 'Afrikaans',
    Oshiwambo: 'Oshiwambo',
    'All Notifications': 'Alle Kennisgewings',
    'Critical Alerts': 'Kritiese Waarskuwings',
    'Bookings': 'Besprekings',
    'System Updates': 'Stelselopdaterings',
    'Last 24 Hours': 'Laaste 24 Uur',
    'Last 7 Days': 'Laaste 7 Dae',
    'Last 30 Days': 'Laaste 30 Dae',
    'All Time': 'Alle Tye',
    'Urgent Maintenance Required': 'Dringende Instandhouding Vereis',
    'Service Confirmation': 'Diensbevestiging',
    'Vehicle Return Complete': 'Voertuigterugsending Voltooi',
    'System Update Successful': 'Stelselopdatering Suksesvol',
    'Speed Threshold Alert': 'Spoeddrempelwaarskuwing',
    'SCHEDULE NOW': 'BEPLAN NOU',
    'DISMISS': 'WEIER',

    notif_settings: 'Kies waaroor jy in kennis gestel wil word',
    email_notif: 'E-pos Kennisgewings',
    email_notif_sub: 'Ontvang opsommende verslae and waarskuwings via e-pos',
    push_notif: 'Stootkennisgewings',
    push_notif_sub: 'Intydse waarskuwings op jou webblaaier/toestel',
    maint_alerts: 'Instandhoudingswaarskuwings',
    maint_alerts_sub: 'Word in kennis gestel wanneer n voertuig dringende diens benodig',
    promo_offers: 'Promosie-aanbiedinge',
    promo_offers_sub: 'Bly op hoogte van diensafslag en belonings',
    preferences: 'Voorkeure',
    customize_ui: 'Pasmaak die koppelvlak en vertoon',
    theme_mode: 'Tema-modus',
    light: 'Lig',
    dark: 'Donker',
    language_label: 'Taal',
    security_support: 'Sekuriteit & Ondersteuning',
    privacy_sub: 'Bestuur jou data en privaatheidinstellings',
    legal_sub: 'Diensvoorwaardes en wetlike ooreenkoms',

    // Kontroleskerm
    maintenance_activity: 'Oorsig van Instandhoudingsaktiwiteit',
    alerts: 'Waarskuwings',
    open_alerts: 'Oop Waarskuwings',
    closed_alerts: 'Geslote Waarskuwings',
    last_7_months: 'Laaste 7 maande',
    vehicle_status: 'Voertuigstatus',
    no: 'Nr',
    vehicle: 'Voertuig',
    last_service: 'Laaste Diens',
    mileage: 'Kilometers',
    risk: 'Risiko',
    limited_offer: 'Beperkte Tydaanbod',
    off_20: '20% Af',
    brake_service: 'Remdiens',
    book_now: 'Bespreek Nou',
    ai_insight: 'KI Inligting',
    ai_prediction: 'Instandhouding waarskynlik nodig in 2 weke vir 3 voertuie',
    view_details: 'Bekyk Besonderhede',
    dismiss: 'Verwerp',

    add_vehicle: 'Voeg Voertuig By',
    empty_slot: 'Leë Slot',
    vin: 'VIN',
    odometer: 'Kilometerteller',
    pickup: 'Bakkie',
    suv: 'Suf',
    sedan: 'Sedan',
    van: 'Paneelwa',
    truck: 'Vragmotor',
    diesel: 'Diesel',
    gasoline: 'Petrol',
    electric: 'Elektries',
    hybrid: 'Hibried',
    vehicle_info: 'Voertuiginligting',
    make: 'Handelsmerk',
    model: 'Model',
    year: 'Jaar',
    engine_cc: 'Enjin CC',
    engine_type: 'Enjintipe',
    transmission: 'Transmissie',
    fuel_capacity: 'Brandstofkapasiteit',
    last_service_date: 'Laaste Diensdatum',
    in_operation: 'In Werking',
    edit_info: 'Wysig Inligting',
    current_mileage: 'Huidige Kilometers',
    license_plate: 'Nommerplaat',
    vehicle_type: 'Voertuigtipe',
    fuel_type: 'Brandstoftipe',
    service_interval: 'Diensinterval',
    vehicle_image: 'Voertuigbeeld',
    upload_vehicle_image: 'Laai Voertuigbeeld Op',
    notes: 'Notas',
    add_additional_details: 'Voeg enige bykomende besonderhede by...',
    image_uploaded: 'Beeld opgelaai!',
    upload_failed: 'Oplaai het misluk',
    vehicle_added_successfully: 'Voertuig suksesvol bygevoeg!',
    failed_to_add_vehicle: 'Kon nie voertuig byvoeg nie',
    changes_saved: 'Veranderinge gestoor!',
    failed_to_update: 'Opdatering het misluk',
    delete_vehicle_confirmation: 'Skrap hierdie voertuig? Hierdie aksie kan nie ongedaan gemaak word nie.',
    vehicle_removed: 'Voertuig verwyder',
    failed_to_delete: 'Skrapping het misluk',
    edit_vehicle: 'Wysig Voertuig',
    uploading: 'Laai tans...',
    replace_image: 'Vervang Beeld',
    maintenance_summary: 'Instandhoudingsopsomming',
    next_service_due: 'Volgende Diens Verskuldig',
    health_score: 'Gesonheidspunt',
    delete_vehicle: 'Skrap Voertuig',
    vehicle_information: 'Voertuiginligting',
    select: 'Kies',

    total_logs: 'Totale Protokolle',
    active_alerts: 'Aktiewe Waarskuwings',
    completed_ytd: 'Voltooi (YTD)',
    ai_predicted_30d: 'KI-Voorspel (30D)',
    all_vehicles: 'Alle Voertuie',
    export: 'Voer Uit',
    add_service: 'Voeg Diens By',
    next_maint: 'Volgende Instandhouding',
    est_cost: 'Beraamde Koste',
    confidence: 'Vertroue',
    upcoming: 'Opkomende',
    window_30d: '30D Venster',
    maint_tip: 'Instandhoudingswenk',
    assistance: 'Benodig u hulp?',
    call_help: 'Bel Padbystand',
    delete_entry: 'Skrap Inskrywing',
    update_service: 'Dateer Diens Op',
    service_cost: 'Dienskoste',
    tech_loc: 'Tegnikus / Lokasie',
    service_details: 'Diensbesonderhede',
    status: 'Status',
    date: 'Datum',
    record_deleted: 'Rekord geskrap',
    failed_to_delete_record: 'Kon nie rekord skrap nie',
    delete_record_confirmation: 'Is u seker u wil hierdie rekord skrap?',
    status_updated: 'Status opgedateer na',
    failed_to_update_status: 'Kon nie status opdateer nie',
    alert_status_updated: 'Waarskuwingstatus opgedateer',
    service: 'Diens',
    recorded_on: 'Aangeteken op',
    mileage_at_service: 'Kilometers by diens',
    service_summary: 'Diensopsomming',
    type: 'Tipe',
    total_cost: 'Totale Koste',
    detailed_notes: 'Gedetailleerde Notas',
    set_status: 'Stel Status',
    select_vehicle: 'Kies Voertuig',
    oil_change: 'Olieverversing',
    brake_change: 'Remvervanging',
    engine_check: 'Enjinkontrol',
    edit_service: 'Wysig Diens',
    go_to_login: 'Gaan na Login',
    from_last_week: 'vanaf verlede week',
    investment: 'belegging',
    records: 'rekords',
    tasks: 'take',
    urgent_maintenance_required: 'Dringende Instandhouding Vereis',
    service_confirmation: 'Diensbevestiging',
    vehicle_return_complete: 'Voertuigterugsending Voltooi',
    system_update_successful: 'Stelselopdatering Suksesvol',
    speed_threshold_alert: 'Spoeddrimpel Waarskuwing',
    schedule_now: 'BEPLAN NOU',
    dismiss_upper: 'VERWERP',
    all_notif_cat: 'Alle Kennisgewings',
    crit_alerts_cat: 'Kritiese Waarskuwings',
    bookings_cat: 'Besprekings',
    sys_updates_cat: 'Stelselopdaterings',
    last_24h: 'Laaste 24 Uur',
    last_7d: 'Laaste 7 Dae',
    last_30d: 'Laaste 30 Dae',
    all_time_dr: 'Alle Tye',
    maintenance_forecast: 'Instandhoudingsvoorspelling',
    detailed_analysis: 'Gedetailleerde Analise',
    schedule_all_services: 'Beplan Alle Dienste',
    risk_none: 'Geen',
    risk_low: 'Laag',
    risk_medium: 'Medium',
    risk_high: 'Hoog',
    brake_wear: 'Remslytasie',
    engine_oil: 'Enjinstof',
    tire_health: 'Bandgesondheid',
    battery: 'Battery',
    ai_garage_insights: 'KI Motorhuis Inligting',
    predictive_analysis: 'Voorspellende instandhoudingsanalise vir jou vloot',

    bookings_title: 'Diensbesprekings',
    new_booking: 'Nuwe Bespreking',
    calendar: 'Kalender',
    list_view: 'Lysaansig',
    today: 'Vandag',
    month: 'Maand',
    week: 'Week',
    day: 'Dag',
    time: 'Tyd',
    more: 'meer',
    service_center: 'Dienssentrum',
    service_details_title: 'Diensbesonderhede',
    select_service_center: 'Kies Dienssentrum',
    location_address: 'Lokasie Adres',
    preferred_date: 'Voorkeurdatum',
    preferred_time_slot: 'Voorkeurtydgleuf',
    special_instructions: 'Spesiale Instruksies',
    confirm_booking: 'Bevestig Bespreking',
    booking_summary: 'Besprekingsopsomming',
    estimated_duration: 'Beraamde Duur',
    estimated_cost_label: 'Beraamde Koste',
    cost_estimate_note: 'Koste is n skatting gebaseer op standaard arbeidstariewe en onderdele. Finale prys kan verskil.',
    technician: 'Tegnikus',
    time_slot: 'Tydgleuf',
    location: 'Lokasie',
    address: 'Adres',
    close_details: 'Maak Besonderhede Toe',
    service_type: 'Dienssoort',
    tire_rotation: 'Bandrotasie',
    full_inspection: 'Volledige Inspeksie',
    appointment_booked: 'Werkswinkelafspraak bespreek!',
    booking_failed: 'Bespreking het misluk',
    session_not_found: 'Gebruikersessie nie gevind nie. Meld asseblief weer aan.',
    gearhouse_garage_placeholder: 'bv. Gearhouse Downtown Garage',
    main_street_placeholder: 'Hoofstraat 123, Sentraal',
    add_special_instructions: 'Voeg enige spesifieke besonderhede of bekommernisse by...',
    main_street_auto: 'Hoofstraat Auto',
    confirmed: 'Bevestig',
    downtown_address: 'Hoofstraat 123, Suite 405',
    delete_record_confirm: 'Is jy seker jy wil hierdie rekord uitvee?',
    maint_added_success: 'Instandhouding suksesvol bygevoeg',
    maint_update_success: 'Instandhouding suksesvol opgedateer',
    failed_add_record: 'Kon nie rekord byvoeg nie',
    failed_update_record: 'Kon nie rekord opdateer nie',
    failed_delete_record: 'Kon nie rekord uitvee nie',
    status_updated_to: 'Status opgedateer na',
    alert_status_updated_msg: 'Waarskuwingstatus opgedateer',
    completed_status: 'Voltooi',
    open_status: 'Oop',
    overdue_status: 'Agterstallig',
    optimize_schedule: 'Optimaliseer Skedule',
    no_upcoming_tasks: 'Geen komende take nie',
    service_in: 'Diens in',
    est_cost_upper: 'RAMINGSKOSTE',
    confidence_upper: 'VERTROUE',
    thirty_day_window: '30-dae Venster',
    pickup_truck_val: 'Bakkie',
    toyota_hilux_db_val: 'Toyota Hilux Dubbelkajuit',
    engine_cc_val: '2 755 cc',
    engine_turbo_val: '2.8L Diesel Turbo',
    trans_auto_val: '6-spoed Outomaties',
    fuel_cap_val: '80 Liter',
    oct_2024_val: '12 Okt 2024',
    next_serv_km_val: '55 200 km',
    low_risk_val: 'LAAG',
    medium_risk_val: 'GEMIDDELD',
    high_risk_val: 'HOOG',
    make_placeholder: 'bv. Toyota',
    model_placeholder: 'bv. Hilux',
    plate_placeholder: 'ABC-1234',
    upload_failed_msg: 'Kon nie beeld oplaai nie',

    all_notif: 'Alle Kennisgewings',
    unread: 'Ongelees',
    archived: 'Gearchiveer',
    mark_all_read: 'Merk alles as gelees',
    no_notif: 'Geen kennisgewings gevind nie',
    unread_alert: 'ongeleeste waarskuwing',
    unread_alerts: 'ongeleeste waarskuwings',
    unread_count_part1: 'Jy het',
    all_caught_up: 'Alles op datum!',
    no_notif_match: 'Geen kennisgewings stem ooreen met jou huidige filters nie.',
    load_older: 'Laai ouer kennisgewings',
    categories_label: 'Kategorieë',
    date_range_label: 'Datumreeks',
    apply_filters: 'Pas Filters Toe',
    clear_all: 'Maak Alles Skoon',
    filters: 'Filters',
    pro_tip: 'PRO-WENK',
    sms_alerts_note: 'Jy kan outomatiese SMS-waarskuwings vir Kritiese en Dringende kennisgewings in jou Rekeninginstellings stel.',
    critical_alerts: 'Kritiese Waarskuwings',
    system_updates: 'Stelselopdaterings',
    last_24_hours: 'Laaste 24 Uur',
    last_7_days: 'Laaste 7 Dae',
    last_30_days: 'Laaste 30 Dae',
    all_time: 'Alle Tye',
    all_notifications: 'Alle Kennisgewings',

    // GearBot
    gearbot: 'Gearbot',
    fleet_assistant: 'Vloot-intelligensie assistent',
    ask_gearbot: 'Vra vir Gearbot...',
    listening_label: 'Luister tans...',
    auto_send_note: 'Outomatiese stuur na 4s stilte...',
    ai_initial_msg: "Haai! Ek is Gearbot, jou vloot-intelligensie assistent. Hoe kan ek jou vandag help?",
    ai_resp_1: "Jou vloot is tans op 92% operasionele kapasiteit. 2 voertuie benodig aandag.",
    ai_resp_2: "Gebaseer op instandhoudingsgeskiedenis, is voertuig GH-102 gereed vir n dienskontrole binne die volgende 3 dae.",
    ai_resp_3: "Ek het 1 kritiese waarskuwing bespeur: n remslytasie-waarskuwing op Tesla Model 3 (GH-102). Beplan instandhouding onmiddellik.",
    ai_resp_4: "Vlootstatistieke: 14 aktiewe voertuie, 2 onder instandhouding, 1 bespreking hangende vir môre.",
    ai_resp_5: "GH-056 se spoeddrimpel is gister op die M1-hoofweg oorskry. Bestuurder: Mike Ross.",
    fleet_owner: "Vlooteienaar",
    open_gearbot: "Maak Gearbot KI oop",
    send_message: "Stuur boodskap",


    profile: 'Profiel',
    security: 'Sekuriteit',
    full_name: 'Volle Naam',
    email_address: 'E-pos Adres',
    phone_number: 'Telefoonnommer',
    change_password: 'Verander Wagwoord',
    sign_out: 'Teken uit',
    profile_updated_successfully: 'Profiel suksesvol opgedateer!',
    manage_profile: 'Bestuur jou persoonlike profiel en sekuriteit',
    owner_manager: 'Voertuigeienaar & Vlootbestuurder',
    active: 'Aktief',
    owner: 'Eienaar',
    download_profile_data: 'Laai Profieldata Af',
    personal_details: 'Persoonlike Besonderhede',
    first_name: 'Voornaam',
    last_name: 'Van',
    account_security: 'Rekeningsekuriteit',
    update_credentials: 'Dateer u rekeningbesonderhede op',
    two_factor_auth: 'Tweefaktor-outentisering',
    extra_security_layer: 'Voeg n ekstra laag sekuriteit by',
    deactivate_account: 'Deaktiveer Rekening',
    current_password: 'Huidige Wagwoord',
    new_password: 'Nuwe Wagwoord',
    confirm_password: 'Bevestig Nuwe Wagwoord',
    password_changed_successfully: 'Wagwoord suksesvol verander!',
    passwords_do_not_match: 'Wagwoorde stem nie ooreen nie',
    deactivate_confirmation: 'Is jy seker jy wil jou rekening deaktiveer? Hierdie aksie kan nie ongedaan gemaak word nie.',
    account_deactivated_successfully: 'Rekening suksesvol gedeaktiveer.',
    upload_profile_image: 'Laai Profielfoto op',
    image_uploaded_successfully: 'Foto suksesvol opgelaai!',
    failed_to_upload_image: 'Kon nie foto oplaai nie.',

    last_updated: 'Laas Opgedateer',
    privacy_1_title: '1. Inligting wat ons versamel',
    privacy_1_text: 'By Gearhouse prioritiseer ons jou privaatheid. Ons versamel inligting wat nodig is om ons vlootbestuursdienste te lewer, insluitend voertuigdata, instandhoudingslogboeke en gebruikersprofiel-inligting.',
    privacy_2_title: '2. Hoe ons data gebruik',
    privacy_2_text: 'Ons gebruik die data wat ons versamel om ons dienste te lewer, in stand te hou en te verbeter, insluitend:',
    privacy_2_li1: 'Verskaffing van voertuiggesondheidswaarskuwings en instandhoudingsvoorspellings.',
    privacy_2_li2: 'Verwerking van transaksies en die bestuur van jou rekening.',
    privacy_2_li3: 'Kommunikasie met jou oor opdaterings en sekuriteit.',
    privacy_3_title: '3. Datasekuriteit',
    privacy_3_text: 'Ons implementeer industriestandaard sekuriteitsmaatreëls om jou professionele en voertuigdata te beskerm. Geen metode van versending oor die internet is egter 100% veilig nie.',
    i_understand: 'Ek verstaan',
    legal_version: 'Weergawe 2.4 — 2026 Vrystelling',
    legal_1_title: 'Regsooreenkoms',
    legal_1_text: 'Hierdie toepassing word verskaf deur P3 Namibia. Deur hierdie diens te gebruik, stem jy in om aan alle plaaslike en internasionale wette rakende vlootbestuur en dataprivaatheid te voldoen.',
    legal_2_title: 'Intellektuele Eiendom',
    legal_2_text: 'Die Gearhouse platform, sy logo en ontwerpelemente is die intellektuele eiendom van Gearhouse Inc. en word beskerm deur kopieregwette.',
    legal_3_title: 'Beperking van Aanspreeklikheid',
    legal_3_text: 'Ons streef na 100% akkuraatheid, maar ons is nie aanspreeklik vir enige afwykings in outomatiese instandhoudingsverslagdoening of GPS-nasporing nie.',
    acknowledge_terms: 'Erken Bepalings'
  },
  'Oshiwambo': {
    dashboard: 'Opamba',
    vehicles: 'Iihauto yandje',
    maintenance: 'Okupangela',
    bookings: 'Omaufuta',
    settings: 'Omaukwatya',
    search: 'Konga...',
    hi: 'Halo',
    garage: 'Tu taleni iihauto yoye nena',
    total_investment: 'Iimali ayihe ya longithwa',
    service_records: 'Onyolo dhomapangelo',
    scheduled_tasks: 'Iilonga ya thanekwa',
    notifications: 'Omatumwalaka',
    privacy_policy: 'Omilandu dhuumwene',
    legal_notice: 'Omatseyitho gopaveta',
    save_changes: 'Hanganitha iinima ayihe',
    cancel: 'Aaye',
    confirm: 'Iyaloo',
    close: 'Edhila',
    loading: 'Tegelela...',
    retry: 'Endulula',
    something_went_wrong: 'Oshinima sha puka',
    error_occurred: 'Oupyakadi wa holoka. Oungudu wetu owa tseyithilwa.',
    back_to_garage: 'Shuna kohauto',
    back_to_settings: 'Shuna komaukwatya',
    my_profile: 'Olupala lwandje',
    logout: 'Za mo',
    signed_in_as: 'Wa za mo mokushengi',
    confirm_logout: 'Owu na uushili kutya owa hala okuzamo?',
    confirm_logout_title: 'Pitapo?',
    confirm_logout_msg: 'Owa lunda kutya owa hala okuzamo mokalata koye ka Gearhouse?',
    yes_sign_out: 'Heeno, Pitapo',
    English: 'Oshiingilisa',
    German: 'Oshindoishi',
    Afrikaans: 'Oshiafrikaans',
    Oshiwambo: 'Oshiwambo',
    'All Notifications': 'Omatumwalaka agehe',
    'Critical Alerts': 'Omatumwalaka omathigu',
    'Bookings': 'Omafuto',
    'System Updates': 'Omapululo',
    'Last 24 Hours': 'Oowola 24 dha pwa',
    'Last 7 Days': 'Omasiku 7 ga pwa',
    'Last 30 Days': 'Omasiku 30 ga pwa',
    'All Time': 'Ethimbo alihe',
    'Urgent Maintenance Required': 'Epanulo lyoitala lya pumbiwa',
    'Service Confirmation': 'Ekoleko lyepanulo',
    'Vehicle Return Complete': 'Egaluko lyohauto lya pwa',
    'System Update Successful': 'Omapululo ga pwa',
    'Speed Threshold Alert': 'Etseyitho lyoshituntu',
    'SCHEDULE NOW': 'PANELA PAIFE',
    'DISMISS': 'EDHILA',
    notif_settings: 'Hogolola shoka u hala omatseyitho',
    email_notif: 'Omatumwalaka gopae-mail',
    email_notif_sub: 'Taamba onyolo nomatumwalaka gopae-mail',
    push_notif: 'Omatseyitho gokofona',
    push_notif_sub: 'Omatseyitho uunake tawu ningwa',
    maint_alerts: 'Omatseyitho gokupangela',
    maint_alerts_sub: 'Tseyithilwa uuna ohauto ya pumbwa okupangelwa',
    promo_offers: 'Omanagano gomepangelo',
    promo_offers_sub: 'Kala u na uuyelele kombinga yoofatelo',
    preferences: 'Omahogololo',
    customize_ui: 'Longulula olupala loye',
    theme_mode: 'Olwaala lwoshikwa',
    light: 'Uuyelele',
    dark: 'Zile',
    language_label: 'Elaka',
    security_support: 'Egamino nomakwatho',
    privacy_sub: 'Pangele uuyelele woye',
    legal_sub: 'Omilandu dhopaveta',

    // Opamba
    maintenance_activity: 'Uuyelele wokupangela',
    alerts: 'Omatseyitho',
    open_alerts: 'Omatseyitho gopaife',
    closed_alerts: 'Omatseyitho ga pwa',
    last_7_months: 'Oomwedhi 7 dha pwa',
    vehicle_status: 'Onkalo yohauto',
    no: 'Onomola',
    vehicle: 'Ohauto',
    last_service: 'Epanulo lwahugunina',
    mileage: 'Oungendjo',
    risk: 'Oupyakadi',
    limited_offer: 'Ehalo lyi na omana',
    off_20: '20% Yi kuthwa ko',
    brake_service: 'Okupangela oombulayi',
    book_now: 'Futa paife',
    ai_insight: 'Uuyelele wongundu',
    ai_prediction: 'Okupangela ohauto otaku ka pumbiwa miiwike iyali',
    view_details: 'Tala uuyelele',
    dismiss: 'Ekala',
    add_vehicle: 'Gwedha po ohauto',
    empty_slot: 'Opunhu ya hupu',
    vin: 'VIN',
    odometer: 'Odometer',
    pickup: 'Bakkie',
    suv: 'SUV',
    sedan: 'Sedan',
    van: 'Van',
    truck: 'Lorry',
    diesel: 'Diesel',
    gasoline: 'Petrol',
    electric: 'Olushono',
    hybrid: 'Hybrid',
    vehicle_info: 'Uuyelele wohauto',
    make: 'Oshike',
    model: 'Ohauto yoshike',
    year: 'Omumvo',
    engine_cc: 'Engine CC',
    engine_type: 'Oludhi lwengine',
    transmission: 'Gearbox',
    fuel_capacity: 'Ogaluna',
    last_service_date: 'Esiku lyokupangelwa',
    in_operation: 'Otayi longo',
    edit_info: 'Longulula uuyelele',
    current_mileage: 'Oungendjo gopaife',
    license_plate: 'Onomola yohauto',
    vehicle_type: 'Oludhi lwohauto',
    fuel_type: 'Oludhi lomahooli',
    service_interval: 'Oshikando shokupangela',
    vehicle_image: 'Efano lyohauto',
    upload_vehicle_image: 'Tula mo efano',
    notes: 'Odjandjo',
    add_additional_details: 'Gwedha po uuyelele...',
    image_uploaded: 'Efano lya tulwa mo!',
    upload_failed: 'Efulo lya puka',
    vehicle_added_successfully: 'Ohauto ya gwedhwa po nawa!',
    failed_to_add_vehicle: 'Ohauto ya nyengwa okugwedhwa po',
    changes_saved: 'Omapululo ga tulwa mo!',
    failed_to_update: 'Epulo lya puka',
    delete_vehicle_confirmation: 'Dhenga mo ohauto ndjika?',
    vehicle_removed: 'Ohauto ya kuthwa mo',
    failed_to_delete: 'Ekuthomo lya puka',
    edit_vehicle: 'Longulula ohauto',
    uploading: 'Otayi fulwa...',
    replace_image: 'Pingenitha efano',
    maintenance_summary: 'Uuyelele wokupangela',
    next_service_due: 'Okupangela lwahugunina',
    health_score: 'Onkalo yohauto',
    delete_vehicle: 'Dhenga mo ohauto',
    vehicle_information: 'Uuyelele wohauto',
    select: 'Hogolola',
    total_logs: 'Omapangelo agehe',
    active_alerts: 'Omatseyitho gopaife',
    completed_ytd: 'Ga pwa (YTD)',
    ai_predicted_30d: 'Okupangela (30D)',
    all_vehicles: 'Iihauto ayihe',
    export: 'Tumitha',
    add_service: 'Gwedha epanulo',
    next_maint: 'Okupangela kuta landula',
    est_cost: 'Ofuto ya thanekwa',
    confidence: 'Uushili',
    upcoming: 'Tayiiya',
    window_30d: 'Esiku 30',
    maint_tip: 'Ondunge yokupangela',
    assistance: 'Owa pumbwa ekwatho?',
    call_help: 'Dhenga opolisi',
    delete_entry: 'Dhenga mo',
    update_service: 'Longulula epanulo',
    service_cost: 'Ofuto yepangelo',
    tech_loc: 'Omupangeli / Ehala',
    service_details: 'Uuyelele wepanulo',
    status: 'Onkalo',
    date: 'Esiku',
    record_deleted: 'Oshikando sha kuthwa mo',
    failed_to_delete_record: 'Oshikando sha nyengwa okukuthwa mo',
    delete_record_confirmation: 'Owu na uushili kutya owa hala okukutha mo?',
    status_updated: 'Onkalo ya pingenithwa',
    failed_to_update_status: 'Onkalo ya nyengwa okupingenithwa',
    alert_status_updated: 'Omatseyitho ga pwa',
    service: 'Okupangela',
    recorded_on: 'Sha tulwa mo mesiku',
    mileage_at_service: 'Oungendjo pethimbo lyepanulo',
    service_summary: 'Uuyelele wepanulo',
    type: 'Oludhi',
    total_cost: 'Ondando ayihe',
    detailed_notes: 'Odjandjo ayihe',
    set_status: 'Tula onkalo',
    select_vehicle: 'Hogolola ohauto',
    oil_change: 'Omahooli gengine',
    brake_change: 'Oombulayi',
    engine_check: 'Okutala engine',
    edit_service: 'Longulula epanulo',
    bookings_title: 'Omafuto gepangelo',
    new_booking: 'Ofuto ompe',
    calendar: 'Okatimesha',
    list_view: 'Omusholondondo',
    today: 'Nena',
    month: 'Omwedhi',
    week: 'Oshiwike',
    day: 'Esiku',
    time: 'Ethimbo',
    more: 'Iinima iikwawo',
    service_center: 'Ehala lyokupangela',
    service_details_title: 'Uuyelele wepanulo',
    select_service_center: 'Hogolola ehala',
    location_address: 'Ondungetulo yedhina',
    preferred_date: 'Esiku wa hala',
    preferred_time_slot: 'Ethimbo wa hala',
    special_instructions: 'Omatompelo ga kuthwa ko',
    confirm_booking: 'Koleka ofuto',
    booking_summary: 'Uuyelele wofuto',
    estimated_duration: 'Ethimbo tali pumbwa',
    estimated_cost_label: 'Ofuto ya thanekwa',
    cost_estimate_note: 'Ondando otayi vulu okupingenithwa.',
    technician: 'Omupangeli',
    time_slot: 'Ethimbo',
    location: 'Ehala',
    address: 'Adres',
    close_details: 'Edhila uuyelele',
    service_type: 'Oludhi lwohauto',
    tire_rotation: 'Okupingena omataiyela',
    full_inspection: 'Okutala hauto ayihe',
    appointment_booked: 'Epanulo lya futwa nawa!',
    booking_failed: 'Ofuto lya puka',
    session_not_found: 'Uuyelele woye inawu monika. Shuna mo.',
    gearhouse_garage_placeholder: 'Oshiholelwa: Gearhouse Downtown Garage',
    main_street_placeholder: 'Edhina lyehalo: 123 Ondjila yopokati',
    add_special_instructions: 'Gwedha po uuyelele woye...',
    main_street_auto: 'Ehala lyopokati koshilando',
    confirmed: 'Iyaloo',
    downtown_address: '123 Ondjila yopokati, Ehala 405',
    delete_record_confirm: 'Owu na uushili kutya owa hala okukutha mo?',
    maint_added_success: 'Okupangela kwa gwedhwa po nawa',
    maint_update_success: 'Okupangela kwa tulwa mo nawa',
    failed_add_record: 'Okugwedha po oshikando sha nyengwa',
    failed_update_record: 'Okupingenitha oshikando sha nyengwa',
    failed_delete_record: 'Ekuthomo lyoshikando lya nyengwa',
    status_updated_to: 'Onkalo ya pingenithwa kugu',
    alert_status_updated_msg: 'Omatseyitho ga pingenithwa',
    completed_status: 'Ga pwa',
    open_status: 'Oge li po',
    overdue_status: 'Ga kelelewe',
    optimize_schedule: 'Pingenitha okatimesha',
    no_upcoming_tasks: 'Kaku na iilonga iyapwa',
    service_in: 'Okupangela mu',
    est_cost_upper: 'OFUTO YA THANEKWA',
    confidence_upper: 'UUSHILI',
    thirty_day_window: 'Omasiku 30',
    pickup_truck_val: 'Okatuu ka Pickup',
    toyota_hilux_db_val: 'Toyota Hilux yedhinandundu',
    engine_cc_val: '2,755 cc',
    engine_turbo_val: '2.8L Diesel Turbo',
    trans_auto_val: 'Oautomatika yo 6',
    fuel_cap_val: 'Olitela 80',
    oct_2024_val: '12 Koteba 2024',
    next_serv_km_val: '55,200 km',
    low_risk_val: 'PITHI',
    medium_risk_val: 'POKATI',
    high_risk_val: 'PUIITI',
    make_placeholder: 't.j. Toyota',
    model_placeholder: 't.j. Hilux',
    plate_placeholder: 'ABC-1234',
    upload_failed_msg: 'Oshimpwiyu sha nyengwa okutulwa mo',
    all_notif: 'Omatumwalaka agehe',
    unread: 'Inaga leshwa',
    archived: 'Ga tulwa nawa',
    mark_all_read: 'Koleka kutya oga leshwa',
    no_notif: 'Kaku na omatumwalaka',
    unread_alert: 'etumwalaka inali leshwa',
    unread_alerts: 'omatumwalaka inaga leshwa',
    unread_count_part1: 'Omu na',
    all_caught_up: 'Omapulo ga pwa!',
    no_notif_match: 'Kaku na omatumwalaka ga fa ngoka wa hogolola.',
    load_older: 'Tala omatumwalaka amwe ga pwa',
    categories_label: 'Omagulu',
    date_range_label: 'Omazimbo gomasiku',
    apply_filters: 'Tula po omahogololo',
    clear_all: 'Dhenga mo ayihe',
    filters: 'Omahogololo',
    pro_tip: 'OONDUNGE',
    sms_alerts_note: 'Owu na okuvululula omatumwalaka go-SMS mokuhoholola uuyelele woye.',
    critical_alerts: 'Omatumwalaka omathigu',
    system_updates: 'Omapululo gopaife',
    last_24_hours: 'Oowola 24 dha pwa',
    last_7_days: 'Omasiku 7 ga pwa',
    last_30_days: 'Omasiku 30 ga pwa',
    all_time: 'Ethimbo alihe',
    all_notifications: 'Omatumwalaka agehe',
    gearbot: 'Gearbot',
    fleet_assistant: 'Omukwathi gwohauto yoye',
    ask_gearbot: 'Pula Gearbot...',
    listening_label: 'Otandi pulakene...',
    auto_send_note: 'Tali tumwa uuna kwa pwa uule wethimbo...',
    ai_initial_msg: "Halo! Oame Gearbot, omukwathi gwohauto yoye. Ondi na oku ku kwatha ngiini nena?",
    ai_resp_1: "Iihauto yoye oyo nawa, ihe iyali oya pumbwa okupangelwa.",
    ai_resp_2: "Ohauto GH-102 oya pumbwa okupangelwa miiwike itatu.",
    ai_resp_3: "Ohauto Tesla Model 3 (GH-102) oyi na uupyakadi woombulayi. Pangela yituyituyitu.",
    ai_resp_4: "Uuyelele: Iihauto 14 otayi longo, iyali otayi pangelwa.",
    ai_resp_5: "GH-056 okwa li ta dhindi nayi mesiku lyananena.",
    fleet_owner: "Omwene gwiihauto",
    open_gearbot: "Patulula Gearbot AI",
    send_message: "Tumitha etumwalaka",
    profile: 'Olupala lwondunge',
    security: 'Egamino',
    full_name: 'Edhina alihe',
    email_address: 'E-mail Adres',
    phone_number: 'Onomola yongodhi',
    change_password: 'Pingenitha onomola yoye',
    sign_out: 'Za mo',
    profile_updated_successfully: 'Olupala lwa pingenithwa nawa!',
    manage_profile: 'Pangele uuyelele woye nogegamino',
    owner_manager: 'Omwene nangele omupangela gwiihauto',
    active: 'Otayi longo',
    owner: 'Omwene',
    download_profile_data: 'Nana uuyelele woye',
    personal_details: 'Uuyelele woye mwene',
    first_name: 'Edhina lyotango',
    last_name: 'Van',
    account_security: 'Egamino lyuuyelele',
    update_credentials: 'Longulula uuyelele woye weamino',
    two_factor_auth: 'Egamino lwaali',
    extra_security_layer: 'Gwedha po egamino limwe',
    deactivate_account: 'Dhenga mo olupala loye',
    current_password: 'Oshitya shegameno shagopaife',
    new_password: 'Oshitya shegameno oshipe',
    confirm_password: 'Shilipaleka oshitya shegameno oshipe',
    password_changed_successfully: 'Oshitya shegameno sha lundululwa nawa!',
    passwords_do_not_match: 'Iitya yegameno iyali inayi faathana',
    deactivate_confirmation: 'Oshili wa hala u dhimunine po okonto yoye? Kayi na oku galuulwa we.',
    account_deactivated_successfully: 'Okonto ya dhimunwa po nawa.',
    upload_profile_image: 'Gwedha po efano lyoye',
    image_uploaded_successfully: 'Efano lya gwedhwa po nawa!',
    failed_to_upload_image: 'Efano inali gwedhwa po.',
    last_updated: 'Lwahugunina lwa tulwa mo',
    privacy_1_title: '1. Uuyelele tawu kongwa',
    privacy_1_text: 'Otu na uushili kutya uuyelele woye owe gaminwa.',
    privacy_2_title: '2. Omukalo tatu longitha uuyelele',
    privacy_2_text: 'Otu na ekwatho netulopo lyopashinanena lyuuyelele woye.',
    privacy_2_li1: 'Egamino nomatseyitho gohauto.',
    privacy_2_li2: 'Omafuto nangele olupala lwoye.',
    privacy_2_li3: 'Okutseyithilwa uuyelele omupyakadi.',
    privacy_3_title: '3. Egamino lyuuyelele',
    privacy_3_text: 'Otu na omikalo omathigu okunamina uuyelele woye.',
    i_understand: 'Ondu uve ko',
    legal_version: 'Oludhi 2.4 — 2026',
    legal_1_title: 'Euvathano lyopaveta',
    legal_1_text: 'Oshinima shika oshi na ekonakono lya P3 Namibia.',
    legal_2_title: 'Iinima yetu',
    legal_2_text: 'Gearhouse oha simanekwa paveta.',
    legal_3_title: 'Omauthitho',
    legal_3_text: 'Otu na uushili ihe katu na ondjo ngele uuyelele wontu puka.',
    acknowledge_terms: 'Koleka omauthitho',
    go_to_login: 'Shuna kohauto (Login)',
    from_last_week: 'kosho iwike ya pwa',
    investment: 'iimali ya longithwa',
    records: 'onyolo',
    tasks: 'iilonga',
    urgent_maintenance_required: 'Epanulo lyoitala lya pumbiwa',
    service_confirmation: 'Ekoleko lyepanulo',
    vehicle_return_complete: 'Egaluko lyohauto lya pwa',
    system_update_successful: 'Omapululo ga pwa',
    speed_threshold_alert: 'Etseyitho lyoshituntu',
    schedule_now: 'PANELA PAIFE',
    dismiss_upper: 'EDHILA',
    all_notif_cat: 'Omatumwalaka agehe',
    crit_alerts_cat: 'Omatumwalaka omathigu',
    bookings_cat: 'Omafuto',
    sys_updates_cat: 'Omapululo',
    last_24h: 'Oowola 24 dha pwa',
    last_7d: 'Omasiku 7 ga pwa',
    last_30d: 'Omasiku 30 ga pwa',
    all_time_dr: 'Ethimbo alihe',
    maintenance_forecast: 'Ethanekolo lyokupangela',
    detailed_analysis: 'Ekonaakono lyuule',
    schedule_all_services: 'Thaneka omapangelo agehe',
    risk_none: 'Kaku na',
    risk_low: 'Oshishona',
    risk_medium: 'Opokati',
    risk_high: 'Oshinene',
    brake_wear: 'Oombulayi',
    engine_oil: 'Omahooli gengine',
    tire_health: 'Omataiyela',
    battery: 'Battery',
    ai_garage_insights: 'Uuyelele wongundu',
    predictive_analysis: 'Ekonaakono lyothanekolo yepangelo rwohauto yoye',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    if (saved === 'English (US)') return 'English'; // Migration
    return (saved as Language) || 'English';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string) => {
    const langSet = translations[language] || translations['English'];
    return langSet[key] || translations['English'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
